<a href="https://colab.research.google.com/github/dabarbosa10/DataPrepInter/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
names = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
dr =  [True, False, False, False, True, True, True]
cpc = [809, 731, 588, 18, 200, 70, 45]

In [2]:
import pandas as pd

In [9]:
my_dict={
    'country':names,
    'drives_right':dr,
    'cars_per_cap':cpc
}

In [10]:
cars=pd.DataFrame(my_dict)

In [11]:
cars

country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
3          India         False            18
4         Russia          True           200
5        Morocco          True            70
6          Egypt          True            45

In [12]:
row_labels = ['US', 'AUS', 'JPN', 'IN', 'RU', 'MOR', 'EG']
cars.index=row_labels

In [13]:
cars

country  drives_right  cars_per_cap
US   United States          True           809
AUS      Australia         False           731
JPN          Japan         False           588
IN           India         False            18
RU          Russia          True           200
MOR        Morocco          True            70
EG           Egypt          True            45

In [16]:
cars['country']

US     United States
AUS        Australia
JPN            Japan
IN             India
RU            Russia
MOR          Morocco
EG             Egypt
Name: country, dtype: object

In [17]:
cars[['country']]

country
US   United States
AUS      Australia
JPN          Japan
IN           India
RU          Russia
MOR        Morocco
EG           Egypt

In [20]:
cars.loc[["RU","AUS"],["country","cars_per_cap"]]

country  cars_per_cap
RU      Russia           200
AUS  Australia           731

In [21]:
cars.loc[:, ["country"]]

country
US   United States
AUS      Australia
JPN          Japan
IN           India
RU          Russia
MOR        Morocco
EG           Egypt

In [22]:
"carl"<"diego"

True

In [23]:
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

In [24]:
my_house[my_house>=18]

array([18., 20.])

In [25]:
my_house[my_house<your_house]

array([20.  , 10.75])

In [26]:
my_house>=18

array([ True,  True, False, False])

In [27]:
bmi=np.array([21.852, 20.975, 21.75, 24.747, 21.441])

In [28]:
bmi>21

array([ True, False,  True,  True,  True])

In [29]:
bmi<22

array([ True,  True,  True, False,  True])

In [30]:
np.logical_and(bmi>21, bmi<22)

array([ True, False,  True, False,  True])

In [31]:
bmi[np.logical_and(bmi>21, bmi<22)]

array([21.852, 21.75 , 21.441])

In [32]:
#lets work with this numpy arrays

In [33]:
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])


In [34]:
np.logical_or(my_house>18.5, my_house<10)

array([False,  True, False,  True])

In [35]:
np.logical_and(my_house<11, your_house<11)

array([False, False, False,  True])

dataframe["area"]>8

is_huge=dataframe["area"]>8

dataframe[is_huge]




In [36]:
cars

country  drives_right  cars_per_cap
US   United States          True           809
AUS      Australia         False           731
JPN          Japan         False           588
IN           India         False            18
RU          Russia          True           200
MOR        Morocco          True            70
EG           Egypt          True            45

In [38]:
cars[np.logical_and(cars['cars_per_cap']>200, cars['cars_per_cap']<800)]

country  drives_right  cars_per_cap
AUS  Australia         False           731
JPN      Japan         False           588

In [39]:
dr=cars['drives_right']

In [40]:
dr

US      True
AUS    False
JPN    False
IN     False
RU      True
MOR     True
EG      True
Name: drives_right, dtype: bool

In [41]:
cars[dr]

country  drives_right  cars_per_cap
US   United States          True           809
RU          Russia          True           200
MOR        Morocco          True            70
EG           Egypt          True            45

In [42]:
for index, value in enumerate(cpc):
  print(f'The index is {index} and the value is {value}')

The index is 0 and the value is 809
The index is 1 and the value is 731
The index is 2 and the value is 588
The index is 3 and the value is 18
The index is 4 and the value is 200
The index is 5 and the value is 70
The index is 6 and the value is 45


In [43]:
#Now lets take a string
st="Hello World"
for index, character in enumerate(st):
  print(f'The index is {index} and the character is {character}')

The index is 0 and the character is H
The index is 1 and the character is e
The index is 2 and the character is l
The index is 3 and the character is l
The index is 4 and the character is o
The index is 5 and the character is  
The index is 6 and the character is W
The index is 7 and the character is o
The index is 8 and the character is r
The index is 9 and the character is l
The index is 10 and the character is d
